# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Java CI

on: [push, pull_request]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 8, 11, 17 ]

    steps:
    - uses: actions/checkout@v3
      with:
        persist-credentials: false
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: ${{ matrix.java }}
        cache: 'maven'
    - name: Build with Maven
      # Use the default goal
      if: matrix.java == 8
      run: mvn -V --no-transfer-progress
    - name: Build with Maven including examples
      # Examples require Java 11+.
      # Building javadoc errors when run with the package phase with an error about
      # the module path and the unamed module (despite using an automatic module name).
      # Here we run the build and javadoc generation separately.
      if: matrix.java > 8
      run: |
        mvn -V --no-transfer-progress -P commons-numbers-examples -Dmaven.javadoc.skip
        mvn -P commons-numbers-examples javadoc:javadoc
